#!/usr/bin/env bash
# setup.sh — interactive setup for the telegram skill
# Creates ~/.claude/.telegram-config and installs the launchd plist

set -euo pipefail

SKILL_DIR="${HOME}/.agents/skills/telegram"
CONFIG_FILE="${HOME}/.claude/.telegram-config"
PLIST_DIR="${HOME}/Library/LaunchAgents"
PLIST_NAME="com.claude.telegram-poller.plist"
PLIST_PATH="${PLIST_DIR}/${PLIST_NAME}"
POLLER_SCRIPT="${SKILL_DIR}/scripts/telegram-poller.sh"
LOG_DIR="${HOME}/.claude/logs"

echo "=== Telegram Skill Setup ==="
echo ""

# --- Config ---
if [[ -f "$CONFIG_FILE" ]]; then
  echo "Config already exists at $CONFIG_FILE"
  read -rp "Overwrite? (y/N) " OVERWRITE
  if [[ "$OVERWRITE" != "y" && "$OVERWRITE" != "Y" ]]; then
    echo "Keeping existing config."
  else
    rm -f "$CONFIG_FILE"
  fi
fi

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "You need a Telegram bot. If you don't have one:"
  echo "  1. Open Telegram and message @BotFather"
  echo "  2. Send /newbot and follow instructions"
  echo "  3. Copy the token it gives you"
  echo ""
  echo "To find your Chat ID:"
  echo "  1. Send any message to your bot"
  echo "  2. Visit: https://api.telegram.org/bot<YOUR_TOKEN>/getUpdates"
  echo "  3. Look for result[0].message.chat.id"
  echo ""
  read -rp "Enter your Telegram Bot Token: " BOT_TOKEN
  read -rp "Enter your Telegram Chat ID: " CHAT_ID

  cat > "$CONFIG_FILE" <<EOF
# Telegram Skill Configuration
# Generated by setup.sh on $(date)
TELEGRAM_BOT_TOKEN="${BOT_TOKEN}"
TELEGRAM_CHAT_ID="${CHAT_ID}"
EOF

  chmod 600 "$CONFIG_FILE"
  echo "Config written to $CONFIG_FILE (mode 600)"
fi

# --- Script permissions ---
chmod +x "${SKILL_DIR}/scripts/telegram-send.sh"
chmod +x "${SKILL_DIR}/scripts/telegram-ask.sh"
chmod +x "${SKILL_DIR}/scripts/telegram-poller.sh"
echo "Script permissions set."

# --- Log directory ---
mkdir -p "$LOG_DIR"

# --- Symlink ---
SYMLINK="${HOME}/.claude/skills/telegram"
if [[ ! -L "$SYMLINK" ]]; then
  ln -s "${SKILL_DIR}" "$SYMLINK"
  echo "Symlink created: $SYMLINK -> $SKILL_DIR"
else
  echo "Symlink already exists: $SYMLINK"
fi

# --- launchd plist ---
mkdir -p "$PLIST_DIR"

cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.claude.telegram-poller</string>

    <key>ProgramArguments</key>
    <array>
      <string>/bin/bash</string>
      <string>${POLLER_SCRIPT}</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <true/>

    <key>StandardOutPath</key>
    <string>${LOG_DIR}/telegram-poller.log</string>

    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/telegram-poller-error.log</string>

    <key>ThrottleInterval</key>
    <integer>10</integer>
  </dict>
</plist>
EOF

echo "Plist written to $PLIST_PATH"

# --- Load daemon ---
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"
echo "Daemon loaded."

echo ""
echo "=== Setup complete ==="
echo ""
echo "Test informational send:"
echo "  ~/.agents/skills/telegram/scripts/telegram-send.sh \"Hello from Claude!\""
echo ""
echo "Test blocking ask:"
echo "  REPLY=\$(~/.agents/skills/telegram/scripts/telegram-ask.sh \"Reply with anything\"); echo \"Got: \$REPLY\""
echo ""
echo "Check daemon status:"
echo "  launchctl list | grep telegram-poller"
echo "  tail -f ~/.claude/logs/telegram-poller.log"
